project:
  type: website

execute:
  freeze: auto

website:
  title: "Cristian Dinu"
  favicon: images/favicon.png
  image: images/favicon.jpg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts/index.qmd
        text: Articles
      - href: /2025-07-ARC-Festival/
        text: MCP Talk
  site-url: https://cdi.nu
  repo-url: https://github.com/cdinu/cdinu.github.io
  description: "Cristian Dinu is a Senior Research Software Engineer at UCL, building human-centred data systems for climate and energy research, including SERL and EDOL."
  open-graph:
    title: "Cristian Dinu, Building Research Software for a Decarbonised Future"
    description: "Research Software Engineer at UCL working at the intersection of energy, data, and climate. Leading development of SERL and EDOL platforms."
  twitter-card:
    title: "Cristian Dinu, Research Software Engineer"
    description: "I build data platforms for energy and climate research. Currently working on SERL and EDOL at UCL."
  page-footer:
    left: "Copyright 2025, Cristian Dinu"
    right: 
      - icon: github
        href: https://github.com/cdinu/cdinu.github.io
format:
  html:
    respect-user-color-scheme: true
    theme:
      light: [journal, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    css: styles.css
    toc: false
    link-external-newwindow: true
