---
title: "Dacă toate tavanele ar fi ecrane..."
date: "2012-06-19"
time: "07:00"
tags:
  - "ce am mai scris"
  - "nonfictiune"
  - "opinie"
---
Dacă toate tavanele ar fi ecrane și oricine ar putea să afișeze orice pe ele, oare câți ar alege să-și pună deasupra capului o imagine cu cerul? Probabil majoritatea, dar fără să aibă vreun motiv; vor face acest lucru pentru că așa simt ei că trebuie. Ar putea să aibă știrile, ar putea să îl folosească ca pe o oglindă, ar putea pune o operă de artă pe fiecare tavan. Majoritatea insa ar prefera cerul sau albul pereților să fie mereu pe tavanele lor.

Așa s-a întâmplat de fiecare dată. Radioul a fost la început un ziar cu sunet, televiziunea un radio cu imagine, mașinile, căruțe cu motor. Pentru că saltul mental necesită creativitate, intuiție și mai alex experimentare.

Pe tavanele lor cu ecran, oamenii își vor pune mai întâi cerul, apoi niște pionieri le vor arăta cum un lucru care există poate fi pus acolo sus, modificat doar puțin. Apoi alți pionieri creatori vor face ceva cu totul special și neimaginat pentru ei, ceva ce îi va consolida tavanului menirea.

La Read Forward încercăm să fim acei pionieri și creatori ai culturii digitale noi. Avem în stânga vastitatea culturii create până acum, în dreapta tehnologia care este clar cu un pas înainte, iar în fața noastră un viitor pe care îl vrem cât mai aproape și în care să împreunăm cele două entități pe care le percepem diferit.

Noi, oamenii, am creat niște dispozitive cu mai multe simțuri și pe alocuri cu mai multă inteligență decât a noastră. Tableta este o carte care știe unde se află, cum este vremea afară, o carte care își poate schimba forma și (de ce nu) fondul în funcție de starea celui ce îi consumă experiența, din fluxul de Facebook ori din numărul de cuvinte de bucurie apărute în tweet-urile prietenilor săi. Tableta este o scenă care poate fi atinsă, scuturată, "actorii" de pe ea pot să fie fericiți sau triști în funcție de vremea de afară sau de poziția sa față de răsăritul Soarelui. Or de ce nu, aleator complet, o funție a unui liber arbitru al Dumnezeului din mașină.

Suntem în fața unui mare început. Suntem ca niște primi exploratori ai Americii, cu diferența că puțini o știm. Le vom spune tuturor ce pot descoperi. Vom fi alături de artiști pentru a umple tavanele-ecran cu ceea ce nu s-a mai văzut până acum.