---
title: "Ziua națională. De la 10 la 1."
date: "2012-12-01"
time: "07:00"
tags:
  - "ce am mai scris"
  - "nonfictiune"
---
(notițe en-passant)

-   Nu am mai văzut așa puhoi de oameni ieșind din metrou decât dimineața la 8 jumate la Pipera. Azi e la Aviatorilor. Înarmați cu steaguri merg la paradă.

-   Primul reprezentant al statului pe care îl văd este un polițist care se grăbește cu un saxofon spre Herăstrău.

-   Un muzicant ambulant cânta *Deșteaptă-te Române* la o vioară scârțâitoare și dezacordată. Pe gratis. Lângă el stă o femeie pe la 40 de ani cu față de sud-americancă incașă, într-o ie până sub genunchi.

-   Jandarmii arată chiar bine. Au uniformele perfecte și șepcile puse frumos pe cap. Pe lângă ei trece o negresă spre Arcul de Triumf vorbind tare cu accent american.

-   Pe difuzoarele montate pe stâlpi au pus populară: *Să se-audă'n Chișinău că acolo-i neam de-al meu, Să se-audă'n București, Românie să trăiești.*

-   Daria și Rareș sun noii Marii și Ioni ai României. Pe jumătate din copii pare să-i cheme așa.

-   Parada începe. Primele trei straturi de oameni sunt lung și compact lipite de gard. În spatele lor, cei 40 de centimetri rămași până la trotuar sunt disputați respectuos de cetățenii cu categoria 2 de enuziasm național.

-   Sunt priviți cu respect toți, dar aplauze și aprecieri pompierii, SMURD-iștii și cei care au câini pe blindate. Lumea exclamă și arată cu degetul când apar mașini de poliție Logan și Sandero 2.

-   Sunt oameni de toate felurile. Trece pe lângă mine un vlăjgan cu pălărie ca de Bob Marley. Fără rasta. Apoi doi țigănuși simpatici aleargă prin mulțime cu tricolor vopsit pe față.

-   În paralel cu parada militară se desfășoară și una a DSLR-urilor, majoritatea Nikon.

-   "Să învățați bine, da?" le spune un soldat unor copii cu care se conversează zâmbind, în timp ce ei îl privesc cu respect și cu gurile căscate. Dau din cap aprobator.

-   În *Piața Regelui*, câțiva monarhiști se pozează micul mon . Sunt mai puțini decât cei care se uitau pe gardul ambasadei de vis-a-vis la poze cu "Rusia Azi".

-   Semafoarelele luminează netulburate pe Kiseleff. Copiii s-au suit pe blindatele care s-au oprit după paradă pentru a fi admirate. Puhoiul de lume curge pe lângă.

-   Înapoi în metrou, la Victoriei. Un grup de adolescenți întreabă "Ăsta merge la Unirii?". Când aud că da, sar entuziaști în trenul plin de steaguri, panglicuțe, brioșe și chiar unghii tricolore.

-   La Unirii sus, un alt muzicant ambulant scârție zâmbind un fragment clasic, la doi metri de intrarea la *Stradivarius*.

-   Îmi prind steagul de rucsac și pedalez spre muncă. Acum este rândul meu să fac paradă.