---
title: "Amor amoricios"
date: "2012-12-16"
time: "12:21"
tags:
  - "ce am mai scris"
  - "fictiune"
---
Înainte să mă trezesc azi am visat, inexplicabil, trei fraze șoptite parcă de Caragiale. Restul au venit de la sine, tot inexplicabil.\
Iată-le:

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

--- Îți fu dor de mine, Costele?\
--- Îmi fu, Mărioară, cum să nu-mi fie?

--- Sigur, Costele?\
--- Sigur, Mărioară, sigur...

--- Păi și cum se face că abia acum mă vizitezi, după ce trecură mai bine de opt ore de când te întosăși?\
--- Avusăi de rezolvat niste obligații pentru niste amici. Niște comisioane, pe ici pe colo, întelegi.

--- Hm, comisioane carevasăzică... Ce comisioane? Îmi zise slujnica că te văzu intrand la madam Papadopol, apoi cănd se întorcea de la piața, tu mergeai la restaurant.\
--- Ah, madam Papadopol, da. Am avut să-i duc o scrisoare de la bărba\'su. Shtii doar că a fost plecat cu mine...

--- Dar băba\'su s-a întors acum două zile, Costele.\
--- S-o fi întors, dar a și plecat. Trebuia să-i dau femeii scrisoarea, promisesem doar. Stătui mai mult la dânsa pentru că s-apucă să întrebe una alta și discutarăm... Chestiuni obișnuite, mă-nțelegi. Apoi m-am dus degrabă la restaurant pentru că mi se făcuse foame de la coniacul pe care mi-l servise.

--- Da\" madam Papadopol nu ține băutură în casă, Costele. Nu mai are strop de cănd l-a lăsat pe bărba-so de alcool.\
--- Ă, așa e, ai dreptate Mărioară. Coniac băui de la madam Georgescu, și ei avusăi să-i duc ceva... Da', Mărioară... auzi, de ce ești tu supărata? Nu-ți dădui eu carte poștală de pe unde fusăi?

--- Îmi dăduși, da.\
--- Nu-ti primiși de la mine vorbă prin mătușa Veta că să mă ășepți că mă întorc acuș?

--- Primiii, da.\
--- Nu trimisăi scrisori d\'amor în fiecare săptămână?

--- Trimisăși...\
--- Uite, îți mai adusăi o scrisoare de amor și acu', ca să stai fără griji.

--- De amor? De amor amoricios?\
--- Da, Mărioară...

--- Bine, bine, da-mi-o s-o citesc.\
--- Cum zici tu...

--- Vai ce frumos o scrisăși... "Ochii tăi"... Da... "Focul care mă mistuieșe cănd nu te văz aproape"... Îhî... Semnat, "Al tău pe vecie, cu drag și cu săruturi calde, Costel!"... Acum... acum ieși afară și să nu mai calci aici, canalie!!!\
--- De ce, Mărioară? Ce-ai pățit? Ce-ai cu mine?

--- Pe mine nu mă cheamă "Dragă Ilincuțo", nenorocitule!

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

(București, 16 dec. 2012 )