---
title: "(traducere) Monty Python, Dramaturg și clasa muncitoare"
date: "2012-11-23"
time: "11:10"
tags:
  - "monty python"
  - "traduceri"
---
:::::: iframe
::: {#player}
:::

:::: player-unavailable
# An error occurred. {#an-error-occurred. .message}

::: submessage
[Try watching this video on www.youtube.com](https://www.youtube.com/watch?v=rQDeU6dHX-c){target="_blank"}, or enable JavaScript if it is disabled in your browser.
:::
::::
::::::

*O mamă casnică își șterge mâinle de șorț și poftește un tânăr cu costum în casă.*

**Mama** Oh, tata... uite cine a venit să ne vadă... este Ken al nostru!\
**Tatăl** *(fără să ridice ochii)* Ei da, era și timpul, dacă mă întrebi pe mine.\
**Ken** Nu ești fericit că mă vezi, tată?

**Mama** *(strângându-l de mână, încurajator)* Bineînțeles că este fericit să te vadă, Ken, el...\
**Tata** Gata, femeie, gata! Nu mai vorbi tu pentru mine, vorbesc io. *(se uită fără încredere la Ken)* O, dar ce costum ai, dom'le! Asta se poartă acum acolo la voi în Yorkshire?\
**Ken** Este doar un costum normal, tată... este tot ceea ce am în afară de lucrurile obișnuite.

*Tatăl întoarce privirea cu o expresie dezgustată*

**Mama** Și, Ken, cum îți place jos în mină?\
**Ken** Nu-i așa de rău, mamă... avem niște burghie noi cu plăcuțe de tungsten pentru operațiunile preliminare de extracție a cărbunelui.\
**Mama** O, asta sună foarte interesant, dragul meu...

**Tatăl** Burghie cu tungsten! Ce dracu' sunt alea burghie cu plăcuțe de tungsten?\
**Ken** Este ceva ce se folosește în mineritul cărbunelui, tată.\
**Tatăl** *(imitând ironic)* "Este ceva ce se folosește în mineritul cărbunelui, tată." Ești plin de cuvinte sclifosite de când ai plecat din Londra.

**Ken** O, nu, nu asta din nou.\
**Mama** *(spre Ken)* A avut o zi grea, dragule... noua sa piesă are mâine premiera la Teatrul Național.

**Ken** O ce bine!\
**Tatăl** Bine! *bine*? Ce știi tu despre asta? Ce știi tu despre ce înseamnă să te trezești la cinci dimineața ca să zbori la Paris... pentru ca apoi la prânz să trebuiască să te întorci la teatrul Old Vic pentru o recepție la doisprezeze, trudind toată ziua în interviuri de presă și de televiziune și apoi să te întorci aici la zece, luptându-te cu problema unui homosexual nimfoman implicat în uciderea ritualică a unui cunoscut fotbalist scoțian. Asta înseamnă o zi plină fiule, și să nu uiți asta, auzi?!

**Mama** Nu striga la băiat, tata!\
**Tatăl** Ă? Nu'ția fost suficient de bun Hampstead-ul?! \[n.t. Un cartier influent al Londrei\] .. A trebuit să te duci țopăind la Barnsley, tu și cu proetenii tăi mineri. *(scuipă)*

**Ken** Mineritul cărbunelui este un lucru minunat, tată, dar este ceva ce tu nu vei înțelege niciodată. Uită-te la tine doar!\
**Mama** Oh, Ken! Fii Atent! Știi doar cum se face după câteva romane.

**Tatăl** Hai, băiete, zi. Zi totul! Ce ste greșit cu mine? Zi!\
**Ken** Îți zic eu ce e rău cu tine. Capul îâi este plin cu romane și cu poezi și vii acasă în fiecare seară duhnind a Chateau La Tour...\
**Mama** O, nu, nu fă asta!

**Ken** Și uite-te ce i-ai făcut mamei! Ai distrus-o cu întâlnirile cu staruri de film, cu participarea la premiere și cu organizarea atâtor dejunuri de gală...

**Tatăl** Nu este nimic greș't cu dejunurile de gală, băiete! Am avut parte de mai multe gale decât ai avut tu prânzuri gătite!\
**Mama** O, te rog!

**Tatăl** Aaaaaaaau! *(își încleștează mâinile de durere și se așează punându-le între genunchi)*\
**Mama** O, nu!\
**Ken** Ce este?!\
**Mama** Este crampa scriitorului! \[n.t. o boală a mușchilor mâinii și degetelor\]

**Ken** Nu mi-ai zis niciodată despre asta... **Mama** Nu am vrut să-ți spunem, Kenny!

**Tatăl** Sunt în regulă femeie, doar scoate-l de aici odată!\
**Mama** O, Ken! Ar fi bine să mergi... **Ken** Bine, plec.

**Tatăl** După tot ceea ce am făcut pentru el...

**Ken** *(la ușă)* Într-o zi ai să-ți dai seama că este mai mult în viața asta decât cultura. Este mizerie, și fum și o sudoare adevărată și cinstită!!

**Tatăl** Ieși afară! Ieși afară! IEȘI! .... Muncitor ce ești!

*(Ken pleacă. Liniște șocată. Tatăl merge la masă și scoate husa de pe mașina de scris)*

**Tatăl** Știi, mamă, cred că aici e de o piesă... sună-l pe agent și dă-mi-l.

**Mama** Ăăă, cred că ai dreptate, Frank, ar putea exorima... ar pute exprima o temă vitală a epocii noastre...

**Tatăl** Ăhă.

------------------------------------------------------------------------

Traducere de: Cristian Dinu\
Sursa în limba engleză: \[The Complete Monty Python's Flying Circus; All the Words Volume One\] ([http://www.amazon.com/dp/0679726470](http://www.amazon.com/dp/0679726470){target="_blank"}), pp. 22-23 Episod: Sezonul 1, Episodul 2