---
title: "Exo-anima [ficțiune]"
date: "2011-11-28"
time: "06:43"
tags:
  - "ce am mai scris"
  - "fictiune"
---
Nimeni nu știa cum a apărut acest tânăr în sat. Se zice că era din Capitală și că el singur ceruse Partidului să fie repartizat învățător acolo. Sătenii îl primiseră cum nu se poate mai bine.\
\
La început tânărul declara spre surprinderea tuturor că, împreună cu bibliotecara, tânără și visătoare ca și el, vrea să transforme biblioteca comunală într-un paradis al învățăturii ce va schimba lumea. O lume nouă, despre care activistul comunei era de părere că era la fel de bună, dacă nu chiar mai bună decât cea imaginată de părinții Marx și de Engels în operele lor de căpătâi. Că el și cu ea, pierduți acolo, își trăiau viața perfectă în ținuturile fără de legături serioase cu lumea nebună în care păruseră atât de integrați înainte.\
\
Numai că în sat nu exista nici bibliotecă, nici bibliotecară, ceea ce îi făcea pe oameni să creadă că tânărul era puțin nebun. Acesta era însă jovial și comunicativ, binedispus de fiecare dată când îl vedeau, de aceea îi puteau tolera acest mic neajuns.\
\
Doar un paralelipiped de sticlă și metal, cu colțuri rotunjite și cu un măr mușcat pe spate, pe care îl punea la ureche după ce vibra ușor, părea că îl încordează și că îi tulbură gândurile, dealtfel foarte concentrate pe treaba cu care venise la sat. \[\[MORE\]\] Câteodată din paralelipiped se auzea o șoaptă suavă, altădată niște remarci acide și un *clak* de închis, în urma câruia fața i se făcea neagră, dar după care își picta mutra obișnuită, precum o mască pe fața unui carnavalist venețian apatic, dar cu un zâmbet lat, desenat impecabil.\
\
Toată lumea vroia să știe ce e cu șoaptele, dar mai ales cu celelalte cuvinte, cele rele, care îl distrugeau ușor pe tânăr. Nimeni nu putu afla. Se părea că șoaptele sunt vorbe de dragoste, iar el părea să le împărtășească, așadar trebuie să fi crezut că vorbea singur cu o femeie, poate chiar cu acea bibliotecară. De ce se întuneca așa dintr-o dată, cum era oare posibil, totuși?\
\
Sătenii spun că nici el nu știa. Zice-se că ședea pe gânduri, plimbăndu-se prin școală cu un Snagov în mână, trist fără cauză, bulversat fără voie și angoasat fără explicație. Își ascundea perfect anxietatea față de ceilalți. Ar fi putut fi prins în starea sa reală, doar că cei care s-ar fi putut prinde nu existau. Adică nu acolo și nu atunci.\
\
Tot țăranii spun că ar fi o singură ființă care poate să îi ghicească tânărului gândurile, acea bibliotecară din imaginația lui, doar că aceasta este departe în toate dimensiunile cu excepția celei mentale, atât de aproape de el încât distanța acolo se măsoară cu numere negative. Că prezența ei este un burghiu cu capăt sferic plin de ace ce îi sfredelește "corpus callosum"-ul tânârului învățător.\
\
Babele îi plângeau de milă, spunând că este necuratul cel ce l-a posedat. Tinerele se uitau galeș prin privirile lor senine de ignoranță își chicoteau de fiecare dată vorbe repezi între ele prin dinții galbeni roși de carii.\
\
Pe lângă entuziasmul cu care le vorbea copiilor din sat în timpul zilei, tânărul nu mai interacționa altfel cu nimeni. Se ducea seara singur în odaia sa de la marginea satului și se auzeau șușoteli din când în când sau clămpănelile unor butoane de plastic ale unui obiect negru reflectolizant, în formă de \\\_\_, ca un pian deschis cu un ecran plin de litere. De acolo îi veneau bucurii și frustrari aproape la fel ca din paralelipipedul de sticlă.\
\
În cele din urmă sătenii se hotărâră să vadă totuși ce se întâmplă sub nasul lor și făcură în așa fel încât tânărul să fie chemat cu treabă la primărie o zi întreagă.\
\
L-au chemat repede, așa încât să nu poată să își ia cu el nimic și să lase totul în odaie. La început au crezut că s-au chinuit degeaba, însă sub un divan găsiră niște caiete roșii și un obiect negru cu veșmânt portocaliu, tot din sticlă și fier și cu măr pe spate ca paralelipipedul, numai că mai mare și mai lat.\
\
După un o transcriere rapidă a caietelor și a ceea ce au găsit în al doilea obiect, duseră prada spre cercetare la înțeleptul satului.\
\
Bătrânului îi luă ceva timp să descâlcească firele minții tânărului, așa cum se proiectau ele pe pânzele de celuloză și de biți. Senectutea sa combinată cu mintea analitică și abilitățile de exo-specție au dat rezultate în cele din urmă, cu toate că nimeni nu știa ce este cu acele obiecte care luminează litere când le apeși pe butoane.\
\
Completă un amplu proces-verbal ce fu citit chiar de la ședința de partid:\
\
"Dragă tovarășe Primar, tovarășă Învățătoare, sfințite Părinte,\
\
Se pare că este vorba despre un tânăr complex și cu probleme, ceea ce probabil deja bănuiați.\
\
Mințile sale, deja sub formă destul de vâscoasă au fost supuse unui proces de fierbere ulterior întâlnrii sale mentale cu o anume tânără, pesemne din alte dimensiuni temporale, ceea ce l-a făcut să aibă acel comportament pe care l-ați observat la școală, la mesele cu noi, seara în drum spre casă, la căminul cultural în spectacole et caetera, et caetera.\
\
În urma acestei lichefieri urmate de un proces de vaporizare în cutia sa craniană, tovarăși și tovarășe, tânărul nostru a început să perceapă diferit realitatea. În fața ochilor săi au încput să se lege fire care pentru noi nu există. A început prin a lua paralelipipedul negru lucios în mână cu câteva zeci de secunde înainte să vibreze și să înceapă șoaptele din el.\
\
Apoi a început să fredoneze dimineața melodii pe care le auzea seara cântate de tovărășele anoste venite la noi în delegație de la Județ. Si uneori inventa povești care începeau să se țeasă cu indicii reale în zilele următoare. Ar părea că are puteri magice, dar de fapt credem că tovarășul învățător, aplicând filozofia Omului Nou, a reușit să iasă din timpurile noastre.\
\
Întâlnirea inițială cu această exo-ființă, dragii tovarăși, a fost pentru dânsul trecerea din trei dimensiuni la cea în mai multe dimensiuni, bănuim că cel puțin cinci, dacă puteți să vă închipuiți așa ceva.\
\
Între mințile sale și ale acelei tovarășe imaginare, pe care de acum o voi numi exo-anima -- adică, sufletul său extern extins -- s-a manifestat un fenomen complex, stimați colegi: practic in-anima și exo-anima, sufletele interne și externe s-au contopit mai repede decât in-cerebrum și exo-cerebrum-ul lor -- mințile raționale -- au putut să reacționeze. Procesul lor de fuziune a luat forma unui vârtej al lichidului ani-motic cu precipitate de rațiune care au fost rapid mutate spre în zone mai puțin accesibile.\
\
Acest proces, respectabili consăteni, este unul cât se poate de nefiresc. Pentru că ființele din societatea noastră socialistă se întâlnesc și spun că se se iubesc ad-cerebrum, nu ad-animam, precum specimenele pe care le analizăm în această lucrare.\
\
Reacția de fuziune a fost puternic exotermă. Ambii subiecți au suferit arsuri urmate de perioade compensatorii în care cerebrum-ul lor s-a seaparat. Anima a rămas, iar frigul intern apropiat de zero absolut ce i-a cuprins în urma degajării acelor cantități imense de căldură, a dezvotat o forță de contopire apropiată de infinit.\
\
Cele două entități, distinșii mei ascultători, s-au trezit într-o nouă situație. Corpul și o parte a existenței lor trăiau în niște canoane pe care noi le numim sociale. În schimb tot restul existenței lor era, dacă vă puteți închipui, într-un neant propriu, gol dar de un alb lăptos și luminos în care anima trăia la intensități maxime.\
\
Acest neant infinit are și o materializare tridimensională, care nu a putut fi localizată exact, dar în care Cerebrum domină. Cerebrum le dăunează celor doi pentru că ad-cerebrum ei sunt de cele mai multe ori în plane paralele, ne-euclidiene, care se intersectează cu anima încâlcit creându-le în acesta turbulențe majore.\
\
Frustrările lor, presiunile sociale ce au fost puse asupra lor, limitările lor proprii din lumea aceasta a noastră, au creat adevărate uragane în anima. Uragane care le-au provoacat dureri interminabile. Pasta formată din sufletele lor a devenit solidă și a crăpatat textura pământului Bărăganului nostru în timp de secetă. Este greu de închipuit așa ceva.\
\
Problema este, tovarăși, că cele două entități real-imaginare au o mare limitare. Odată ce au fost împreună nu mai pot fi separați. Și cum ei sunt ținuți separați de propriile limitări și dezamăgiri, această separare le va fi fatală.\
\
De aceea vă recomand stimați fruntași ai satului să facem deja cerere la Minister pentru a ne fi repartizat un nou învățător".\
\
Cerea a fost aprobată și bătrânul a avut dreptate. La câteva zile după ședință, învățătorul a nu a mai venit la școală și nimeni nu l-a mai văzut de atunci. A rămas doar în mințile elevilor săi și în poveștile satului. Se pare că ultima oară ar fi fost văzut în odaia sa de către un curios pus de Partid să îl supravegheze. Acesta le-ar fi spus sătenilor că învățătorul a devenit din ce în ce mai transparent și cu marginile corpului mai difuze într-o ultimă încercare nereușită de a se întâlni cu bibliotecara. Înainte să dispară de tot, într-un gol alb-vâscos.