---
title: "re-covers: Meșterul Manole, MBA"
date: "2011-10-23"
time: "22:20"
tags:
  - "ce am mai scris"
  - "fictiune"
  - "recovers"
---
-- Dragi colegi, este esențial să terminăm acest proiect până la sfârșitul trimestrului curent, pentru că altfel impactul negativ, atât asupra afacerilor clientului cât și asupra operațiunilor companiei noastre sunt extrem de greu de calculat, spuse Manole apăsat, privindu-i pe toți în ochi și făcându-i să-și aducă aminte indirect că vor fi zidiți la propriu cu totul dacă ratează deadline-ul.

Privirile lor păreau să înțeleagă gravitatea situației. Manole ajunsese responsabil cu proiectul de construcție al mânăstirii în urma unui șir mai lung de proiecte pe care le dusese la bun sfârșit fără mari incidente. Mănăstirea este însă de departe proiectul cu cea mai mare anvergură pe care Manole a trebuit să îl conducă în cariera sa. Totul a început bine: clientul părea că știe ce vrea, chiar dacă nu avea maturitatea necesară să înțeleagă cum merg lucrurile în domeniul construcțiilor cu destinație spirituală. În plus, părea că are înțelepciunea să lase echipa să facă ce dorește, lucru care s-a și întâmplat la început.

-- Dar, Manole, răspunde inginerul-șef, știi că ce ne ne ceri este imposibil! Nu am mai avansat în mod real de câteva luni bune, în ciuda tuturor eforturilor pe care le-am făcut, iar toată lumea știe că depășirile peste 20% nu mai pot fi recuperate. Îmbrățișăm constrângerile ca pe niște provocări, e adevărat, dar în ciuda efortului pe care l-am făcut cu toții, valoarea adusă este zero. Ceea ce reușim să construim și să integrăm ziua, noaptea se dărâmă. Ori noi...

-- Mi-ar plăcea să ai o atitudine mai puțin negativă, Dane, îi întrerupse tranșant Manole. Și în loc să îmi spui lucruri pe care le știu deja, aș vrea să te concentrezi la cum putem rezolva ceea ce ai zis mai devreme. Dacă nu facem nimic, sigur treaba nu se va rezolva de la sine. Să știți că este nevoie de o schimbare de paradigmă, schimbare pe care o vom face aici și acum. Nu vreau să ne mai lamentăm și să mai privim în trecut, e clar că soluțiile pe care le-am încercat nu au mers.

Se uită atent la fața fiecăruia. Se văd în fiecare săptămână, în aceeași formulă, cu aceeași lipsă de rezultate. Par că au intrat într-un cerc vicios în care lipsa de rezultate îi demotivează, iar demotivarea face ca lipsa de rezultate să se adâncească. Sunt în total zece oameni, el împreună cu o echipă de nouă: doi meșteri seniori, cinci juniori entuziaști  și doi specialiști în construcții de cărămidă. Zece oameni care nu mai cred în ceea ce fac și care nu mai văd o ieșire onorabilă din această situație.

Nu se grăbi să răspundă. Îi lăsă în liniște, să gândească singuri, pentru prima oară după multă vreme. Pentru că a văzut clar că n-a mers să le bage în cap ideile lui. Își dă seama că singura soluție este să devină doar un facilitator, chiar dacă îi e greu să nu își impună părerea.

Un junior care nu deschisese până atunci gura în vreo întâlnire, îndrăzni în cele din urmă:

-- Știu ce trebuie făcut, Domnu' Manole. Avem nevoie să arătăm că cineva face un sacrificiu enorm, pentru a demonstra atât clientului, cât și lumii ce se întâmplă în caz de eșec. Prima persoană care va intra pe ușă va prelua rolul de consultant extern, coordonator al planului de ieșire din criză. Va fi singura responsabilă pentru eșecul potențial atât al inițiativei, cât și al proiectului mare. Cariera îi va fi distrusă, pentru că o vom zidi în articole de presă ce vor spune că este singurul vinovat, în campanii, conferințe și studii de caz care să demonstreze că noi am fi avut altfel un mare succes. Dacă lucrurile reușesc, atunci meritul va fi evident al nostru, ca echipă. Pentru că suntem oameni, nu o vom distruge direct, o vom lăsa să-și sape singură groapa, ca să zic așa.

Ceilalți opt sunt perplecși de îndrăzneala tânărului, însă după două momente de ezitare, primesc ideea cu urale. Manole nu este de acord, însă trebuie să cedeze destul de repede. Chiar dacă stilul său managerial este destul de autoritar, mai ales în situații de criză, a ales ca de această dată să se supună majorității. Majoritate ce s-ar răscula altfel împotriva sa și în plus, nu are nici el o altă soluție mai bună.

Atunci când pe ușa care se între-deschise apăru capul Anei, regretă însă că nu și-a folosit puterea și intră în panică. Are încredere în Ana, însă complexitatea problemelor de rezolvat și mai ales puternica expunere negativă a inițiativei îl fac să vadă această întâmplare cu cea mai mare neliniște. Plus, ceilalți nu știu că Ana este însărcinată și că peste jumătate de an va trebui să se retragă. Cei-i drept, proiectul trebuie să se termine mult mai repede, așa că acest aspect este oricum irelevant.

-- Vreți ceva de mâncare? Comand acum și poate vă interesează, îi întrebă Ana.

-- Pe Ana aș vrea să nu o implicăm în acest proiect! sări Manole în picioare. Deși expertiza ei în coaching executiv și consultanță în managementul crizei ne-ar fi foarte utile, faptul că suntem într-o relație personală face ca lucrul ei în acest proiect să fie delicat și riscant. În plus etica profesională nu m-a lăsat să îi spun prea multe despre proiect și drept urmare nici nu este de fel familiarizată cu aspectele și provocările pe care le avem.

-- Despre ce proiect este vorba?! Ce etică?! Ce criză?! întrebă Ana bulversată, intrând cu totul în sala de conferințe. Venisem să vă întreb mâncare și voi începeți cu chestii din astea?

-- Uite, Ana, spuse Dan, inginerul-șef, avem o mare oportunitate pentru tine. O oportunitate să te dezvolți atât profesional, cât și personal. Știm că ești un freelancer de top și că acum ești la noi pentru niște consultanță într-un proiect de categoria B, ce este clar mult sub capacitățile tale. Vrem să te aducem în liga mare, unde îți este de fapt locul, și unde poate știi de la Manole că avem niște probleme în finalizarea proiectului cu mânăstirea lui Negru Vodă. Credem că locul tău este aici, în acest proiect. Avem încredere atât de mare în ceea ce poți face încât să te lăsăm să ne îndrumi conform bunelor practici pe care le știi tu. Va trebui însă să îți asumi răspunderea în cazul unui eșec; sper că nu este o problemă.

-- Hmm... Sună interesant, eram sigură de la început că veți da de belele. Ați făcut niște greșeli destul de mari.

Manole făcu ochii mari. Nu îi vine să creadă că Ana îi face una ca asta. Cum adică a făcut greșeli și cum îndrăznește să spună de față cu toți... Intervine scurt:  

-- Cred că scopul a ceea ce încercăm să facem acum nu este să ne uităm spre trecut, ci la ce putem face de azi înainte!

-- Dar Manole, îi spuse Ana, nu ai cum să ignori ce s-a întâmplat până acum în proiect, pentru că este exact șansa să analizezi ce nu merge și ce trebuie să repari. Nu trebuie să iei totul de la zero.

-- Cred ca prima greșeală pe care am făcut-o, interveni Dan,  a fost să acceptăm să începem acest proiect. Sigur, arată bine în portofoliul nostru, se aliniază perfect cu strategia pe care o avem intern ca echipă și companie, dar nu trebuia să acceptăm să lucrăm în niciun fel cu un client care ne amenință că ne zidește dacă nu livrăm ceea ce își dorește.

Manole își amintește bine negocierile Negru Vodă. Părea un client exigent dar rezonabil și faptul că organizația era din sectorul public nu l-a deranjat. Știa că se poate lucra bine cu ea, fiind destul de independentă și auto-susținută în cadrul sistemului guvernamental.

Brief-ul proiectului era foarte simplu: "Vreau o mânăstire de elită, care să nu poată fi comparată cu nimic altceva, atât în țară pe plan global. Vreau ca rezultatul muncii voastre să fie unic și să reflecte atât imaginea pe care doresc să o comunic în piață eu ca persoană, cât și imaginea instituției pe care am creat-o și pe care o conduc. Banii nu sunt o problemă. Aștept o estimare rezonabilă și o voi aproba așa cum este, în schimb vreau ca termenul de livrare să fie de maximum 18 luni. Dacă reușiți, veți primi întreaga sumă plus bonus averi și alte proiecte bănoase de la mine. Dacă nu, va trebui să vă zidesc pe voi. Nu e o chestie personală... așa cere procedura."

 -- A doua greșeală este că am pornit la drum fără specificații complete. A trebuit să cerem sfatul comunității locale în ceea ce privește amplasamentul construcției spirituale, ceea ce ne-a întârziat enorm începerea efectivă a lucrării.

-- A treia greșeală este că stăm să ne luptăm cu problemele, în loc să încercăm să le prevenim. Ar trebui deja să încetăm să mai construim ziua folosind aceleași metode ca până acum. Pentru că dacă nu schimbăm nimic în proces, rezultatele vor fi aceleași și noaptea se va dărâma la loc ce construim peste zi! Ceea ce trebuie să îngropăm nu este un consultant, ci modalitatea noastră de a lucra!

-- A patra greșeală este că nu ne dăm seama că trebuie să comunicăm adevărat. Nu o dată pe săptămână noi cu noi și nu numai la telefon o dată la o lună cu clientul. Trebuie să comunicăm zi de zi, nu numai noi între noi, ci și noi cu ceilalți care sunt implicați în proiect.

-- Iar a cincea greșeală este că nu știm să ne gestionăm bine riscurile și oportunitățile. Sunt lucruri care ne-au luat pe nepregătite, deși știam că se vor întâmpla. Respectiv am ratat ocazii cum a fost ieftinirea materialelor de construcții, pe care nu am fost în stare să le exploatăm, tocmai din cauză că nu am analizat situația cum trebuie.

-- Iată cât de departe ați ajuns, le spuse Ana. Hai să intrăm puțin în detalii la fiecare dintre aceste greșeli și să vedem ce putem aplica de acum înainte...

...Simpla prezență a Anei pare că a descătușat energia grupului.

\* \* \*

În timp, avântul creat în acele momente a ajutat echipa să găsească soluții la problemele pe care le avea. Ana i-a ajutat să găsească ce nu mergea bine și să determine cauzele reale problemelor. I-a ajutat să comunice mai bine între ei și în afară, apoi să depășească limitările pe care și le impuseseră. Au reușit să facă în două luni ceea ce nu făcuseră în celelalte 16 de până atunci, fără resurse în plus, ci numai crescându-și productivitatea.

Un singur incident semnificativ a mai avut loc până la finalizarea proiectului: în ziua acceptanței finale a lucrării cei zece membri ai echipei de proiect se aflau pe acoperiș, pentru a face o poză de grup pe care să o includă în raportul final și în studiul de caz.  Clientul, Negru Vodă i-a întrebat însă dacă mai au puterea să mai facă pentru el, sau pentru altcineva o construcție similară calitativ și funcțional. Manole nu a ezitat să îi răspundă:

-- Având în vedere că acest proiect a fost nu numai o ocazie să ne punem în practică ideile, ci și o școală pentru noi toți, și în plus ținând seama de experiența pe care am acumulat-o, aș putea declara fără ezitare că suntem în stare să facem un proiect cu 50% mai mare în jumătate din timp.

Negru Vodă auzind aceste lucruri a devenit brusc îngrijorat, luând decizia lipsită de etică să dea jos toate scările de pe acoperiș, punând echipa în imposibilitatea de a coborî în siguranță.

Inițial o parte din echipă, care văzuse la televizor Flug Tag, a început să își improvizeze aparate de zbor din materialele de pe acoperiș, chiar și știind că sunt probabil inutile pentru a se da jos. Însă Manole, amintindu-și de lecțiile Anei, a organizat repede o sesiune de brainstorming, spunându-le colegilor:

-- Nu cred că scopul lui Vodă este să ne ucidă direct sau indirect. Nu trebuie să nu luăm acțiunile lui personal și să separăm omul de problemă. Haide să vedem care sunt de fapt interesele lui și să încercăm să îi propunem o soluție win-win.  

-- Dar Manole, este evident că Vodă este supărat că nu va putea să își păstreze avantajul competitiv pe care îl are acum, în contextul în care avansul tehnologic pe care l-am creat micșorează barierele de intrare pentru alți competitori.

Manole înțelese într-o clipă ce este de făcut. Îi rugă pe ceilalți să îl strige împreună pe Vodă, care se opri și se întoarse. În urma discuțiilor, Vodă a înțeles oportunitatea ca echipa să semneze un contract ce conținea o clauză de non-concurență, echipa lui Manole neavând voie să construiască lăcașe spirituale pentru orice religie sau cult în următorii douăzeci și cinci de ani, Vodă obținând în plus și condiții comerciale avantajoase pentru următoarele proiecte civile.

Echipa lui Manole a crescut în următorii ani, ajungând unul dintre principalii furnizori de construcții private și publice. Mânăstirea a rămas în poziția sa dominantă neegalată până în prezent.

Pentru a sărbători înțelegerea și proiectul succesului, pe locul în care Vodă s-a oprit să negocieze cu echipa a fost construită Fântâna Loialității.

--

București, 23 octombrie 2011