---
title: "re-covers: El-Zorab"
date: "2011-11-29"
time: "07:32"
tags:
  - "ce am mai scris"
  - "fictiune"
  - "recovers"
---
Soarele se ridicase doar puțin peste dunele dinspre Bab-el-Manteb, iar frigul nopții din deșert se dezlipea ușor de hainele sărăcăcioase ale lui Ben-Ardun când acesta bătu la porțile micului fort ce apăra granițele Califatului.\
\
Gărzile abia îl băgară în seamă, dar când văzură calul ce îl însoțea, deschiseră curioși ferestruica din poarta masivă.\
--- Ce dorești? îl întrebară. Ce treabă ai tu aici? Și ce faci cu acel cal?\
--- Am venit să i-l vând pașei, măriți ieniceri. Sunt Ben-Ardun din Bab-el-Manteb și am crescut acest cal de când a văzut lumina zilei.\
--- Așteaptă aici! îi spuse cel ce părea să fie șeful lor.\
\
Ben-Ardun se așeză liniștit pe una dintre pietrele rămase de la construcția zidurilor, în timp ce roibul stătea ascultător lângă. Nu după mult timp, poarta se deschise cu totul:\
\
--- Poftește înăuntru. Pașa te primește peste trei ceasuri, îi zise același ienicer ce îi pusese mai devreme să aștepte. Abia aveți vreme să vă odihniți tu și calul.\
\
"Este bine. El-Zorab este la fel de istovit ca și mine după această călătorie", gândi arabul. Calul era într-adevăr obosit și destul de murdar. Abia avură timp să își tragă puțin sufletul și\
un alt ienicer veni și îi conduse pe arab și pe calul lui în grădinile pașei.\
\
Acesta ședea îngândurat, mângâindu-și tihnit barba căruntă. Când văzu calul, se ridică și i se adresă direct lui Ben-Ardun:\
\
--- Înțeleg că vrei să vinzi calul. De unde ai tu un asemenea cal?\
--- Sunt, pașă, neam de beduin. Ne creștem caii singuri, iar pe acesta l-am crescut eu. Mi-e drag ca ochii mei din cap și nu l-aș da nici mort, sunt însă foarte sărac și am nevoie de bani cu orice preț. Oricât îmi dai sunt mulțumit, căci suntem muritori de foame.\
\
Pe măsură ce se uita mai atent la cal, privirea pașei devenea din ce în ce mai aprinsă. Îi plăcea și nici măcar nu încerca să ascundă acest lucru. După câteva momente, făcu direct o ofertă:\
\
--- Îți dau o mie de țechini. Primești?\
--- O, preamărite pașă, da, primesc. Primesc...\
\
Avea lacrimi de fericire în ochi, închipuindu-și anii de bunăstare ce vor urma. Suma era enormă. Copii lui vor merge la școală, nevasta i se va putea îngriji de sănătatea ce îi era așa de șubredă. El nu va mai trebui să se împrumute de la vecinii care deveniseră din ce în ce mai iritați de cererile lui neîntrerupte.\
\
Unul dintre locotenenții pașei îi aduse punga cu bani și Ben-Ardun o luă imediat. Îi era greu încă să creadă că problemele lui toate sunt acum rezolvate. Îl încercă mai întâi un regret că nu a cerut el o sumă mai mare, dar nu, nu ar fi fost în stare să se gândească la atât de mult, oricum. Poate cu acești bani putea să facă și mai mulți... da... viața lui va deveni mult mai bună.\
\
Dar deodată Ben-Ardun avu o revelație sumbră a lumii ce va urma pentru el. O lume fără El-Zorab. O lume în care pustiul nu le va mai cunoaște galopul, o lume în care copii nu se vor mai bucura când ei se vor întoarce acasă. O lume goală.\
\
--- Pașă, vreau calul înapoi, m-am răzgândit. Nu vreau să pierd calul. Fără el viața mea nu mai are sens. Uite banii și lasă-mă să plec!\
\
--- Ben-Ardun, acum calul este al meu și nu este de vânzare.\
\
Arabul se gândea acum și la viața pe care El-Zorab o va avea. Va fi bătut și lăsat flămând. Va muri chinuit de cruzimea pașei și a ienicerilor săi. Scoase un pumnal și sări lângă cal, punându-i-l la grumaz:\
\
--- Îl omor pașă, să știi! Ia banii înapoi și lasă-mă să plec acasă.\
\
Pașa nu se lăsă impresionat. Își dorea calul cu orice preț și răspunse calm:\
\
--- Ben-Ardun, nu fii iresponsabil. Dacă îl omori, ai să pieri și tu, pentru că știi că sunt de neînduplecat atunci când cineva îmi face așa ceva.\
\
--- Nu! Calul este al meu. Nu pot trăi fără el... Mai bine o viață de sărac decât tot restul zilelor să îl știu departe de mine. Știu că murim amândoi! Copii m-or răzbuna cândva.\
\
Arabul ținea vîrful pumnalului sprijinit în continuare de grumazul lui El Zorab. Pașa continuă:\
\
--- Ia-ți familia și te mută în satul de lângă. Dacă vreți să revedeți calul, nu aveți decât să veniți și să-mi vizitați când doriți voi grajdul. Este și în interesul meu ca El Zorab să se adapteze mai ușor aici.\
\
Ben-Ardun păru că se mai liniștește. Poate că pașa se va plictisi de cal, iar el, cu banii pe care îi va face pornind de la ceea ce primește acum, va putea să îl răscumpere. Și oricum, El Zorab nu va fi mai flămând ca acum, ci dimpotrivă bine hrănit, pentru paradă și pentru plăcerea pașei. Îndepărtă pumnalul de grumazul animalului mai întâi puțin, apoi de tot. Căzu în genunchi, plângând de deznădejde, dar știind că face ceea ce trebuie.\
\
Pașa se apropie și îi puse mâna pe umăr, îmbărbătându-l:\
--- Ben-Ardun, nu trebuie să îți fie frică de schimbare. Și ție și familiei tale vă va fi mai bine acum.\
\
Și așa a fost. Cu cei o mie de țechini, Ben-Ardun a schimbat viața sa și pe a familiei sale. A început să crească cai pe care apoi să îi vândă, înzecind mia de țechini în câțiva ani. Impresionat de iubirea arabului pentru animale, pașa îi încredință conducerea grajdurilor sale și i-l înapoie drept răsplată pe El-Zorab. Cu care se zice că și acum se așterne la galop, mergând pe dealuri ca un gând. Din când în când.