---
title: "re-covers: Aripi mentale — Puiul"
date: "2011-10-28"
time: "20:32"
tags:
  - "ce am mai scris"
  - "fictiune"
  - "recovers"
---
M-am născut pe câmp, într-o familie cu mulți frați și o mamă singură. Acolo, în lanul de grâu nimeni nu te ajută. Ne-a crescut pe toți așa cum a știut ea cel mai bine, cu experiența de prepeliță trecută deja prin câteva călătorii.

Viața rurală e liniștită. O trăiești într-o ignoranță pe care am înțeles-o destul de târziu: dimineața sorbi rouă, la prânz te odihnești, apoi seara cauți bobițe care să te sature încă o zi.

Ce n-a înțeles mama de fapt este că sunt diferit de ceilalți. Că eu nu doresc să-mi trăiesc puținii ani având ca principale mize rutina, frica de toți ceilalți și așteptarea următoarei migrațiuni spre Africa.

Am vrut mereu să-mi depășesc condiția de a fi la baza lanțului trofic, iar pentru mine balanța între "luptă sau zboară" nu are cum să încline înspre lașitate ci înspre ambiție și curaj, chiar cu riscul de a pierde tot. Nu îmi este frică să fiu diferit și aș mânca oricând și carne ca să dovedesc asta.

În toate situațiile limită, mama s-a poziționat rapid ca lider și m-a obligat să fac totul conform principiilor ei, nu a năzuințelor mele. Am ales să nu o ascult și de cele mai multe ori nu s-a întâmplat nimic. Am interacționat cu oamenii împotriva dorinței sale. Erau niște oameni simpli ce-i drept, dar tot aș fi vrut să discut mai mult cu ei. Numai că de emoția primei întâlniri, abia am reușit să zic un "piu".

Apoi s-a întâmplat ceea ce am crezut atunci că este nenorocirea maximă: să rămân fără capacitatea de a zbura fizic. Pe câmpul unde crescusem au apărut într-o dimineață de august un vânător cu câinele lui. Ghinionul a făcut să ajungă atât de aproape de noi încât să nu putem evita întâlnirea. L-am observat mai de aproape: după cum era îmbrăcat era clar că vâna din plăcere, nu din nevoie. Evident din partea faunei în care mă aflu, nu pot privi cu ochi buni vânătoarea. Dar pe de altă parte o înțeleg. Diferența etică dintre a vâna o prepeliță și a tăia o găină la vreo fermă avicolă aș spune că înclină mai degrabă înspre vânătoare, pentru că noi pe câmp avem măcar iluzia și șansa să ne trăim zilele până murim de foame sau de ghearele vreunui prădător, nu predestinarea tragică de a ajunge în câteva săptămâni la ofertă în congelatoarele supermarket-urilor.

Mama ne-a spus să stăm pitulați pentru că organizează ea o diversiune, dar într-un moment de furie nu m-am abținut și am zburat. Eram aproape și am vrut să-l atac pe vânător și să-i bag ghearele pe față. Elementul surpriză și-a făcut efectul. Nu se aștepta ca de lângă carâmbul cizmei să apară un dușman mic dar feroce. Eram însă neputincios și nu reușit să-i fac doar o zgârietură pe obraz, ratându-i ochiul. M-a lovit atât de puternic încât m-am prăbușit rostogolindu-mă în țărână. L-am atacat din nou, de data asta ferindu-mă de mâinile sale, însă din nou fără niciun efect. Mă gândesc mereu că dacă săream toți puii pe el reușeam să îl învingem, dar nu e bine să am astfel de pretenții de la ceilalți.

Atunci când a sărit și câinele împotriva mea mi-am dat seama că singura posibilitate de a nu ajunge *strips* este să evadez din acea situație. Am zburat cât am putut de imprevizibil. Am reușit câteva manevre evazive, și părea că am scăpat, însă superioritatea tehnică a speciei sale m-a învins. Când aproape ieșisem din bătaia puștii, a tras din nou și o alică m-a nimerit în aripă. Osul s-a crăpat doar, dar apoi, de la efort, s-a spart de tot. Am căzut într-un lăstăriș, dar unul atât de des și dificil de mers prin el, încât vânătorul nu s-a sinchisit să vină să mă recupereze.

De atunci nu am mai putut să zbor. Durerile cumplite de la început mi-au trecut, însă osul nu s-a refăcut suficient de bine încât să pot să mai folosesc aripa în acel an. Ceea ce mă făcea incapabil să-i urmez în Africa, unde se pregăteau să plece pentru a evita perioada rece de peste iarnă.

Mama a hotărât cu greu să mă lase în urmă și să îi salveze pe ceilalți, ceea ce era normal și de așteptat, nu trebuia să fie o zbatere atât de dură. I-am înțeles decizia, deși pasivitatea ei mă intrigă și acum. Poate ar fi fost util să gândească de la început că soluția nu este să rămână într-o dilemă "ce fac? stau și mor toți sau plec cu ceilalți și moare unul?". Ci "cum pot să găsesc o soluție *out-of-the-box* care să fie benefică pentru toți".

Pe câmp nu sunt spitale, iar mamei nu i-a trecut prin cap că poate ar trebui să meargă în altă parte. Imaturitatea mea, combinată cu imposibilitatea ei de a ieși din tiparele gândirii obișnuite a făcut ca în noiembrie când a venit frigul să mă trezesc singur în pustietate. Nu prea mai era de mâncare și în plus aveam o stare de spirit adânc depresivă. Mă vedeam nu înaintea unei zile proaste, ci a unei ierni în urma căreia aveam să supraviețuiesc. Resemnarea mă cuprinsese și într-o zi aproape că am cedat. Deja noaptea bălțile aproape înghețau, iar roua se transformase de mult în brumă.

Mi-am pus ghearele pline de mocirlă strânse ca de închinăciune, pregătit să mor, însă cu o ultimă tresărire am atins întâmplător pachetul gol de Snagov aruncat în miriște de vreun țăran plictisit de secerat. Am scrijelind spasmatic pe el un **"\|"**. Un **1** ce m-a făcut să mă gândesc la primul lucru pe care l-aș vrea. L-am scris. Apoi totul s-a luminat. Restul le-am scris pe nerăsuflate:

1.  **Nu vreau să mor**

    Nu este momentul.

    Trebuie să trăiesc să iubesc să învăț eu lucruri, să îi învăț pe alții lucruri, să las o moștenire lumii. Trebuie să creez sinergie și echilibru între diversele elemente ale ecosistemului.

2.  **Vreau ca viața mea de aici înainte să conteze cu adevărat**

    Trebuie să îmi împărtășesc viziunea și să îi fac pe toți să se înțeleagă unii cu alții. Vânătorul să înțeleagă că nu este bine să omori din plăcere, iar noi să înțelegem că trebuie uneori să fim mâncați pentru ca cei mari să supraviețuiască.

3.  **Nu sunt o prepeliță fără o aripă, ci o ființă independentă cu două picioare și o aripă bună**

    Zborul este doar una dintre capacitățile mele. Am picioare și creier. Voi compensa pentru această dizabilitate excelând în celelalte calități ale mele.

4.  **Resemnarea și pasivitatea sunt dușmanii mei principali**

    Sunt un pui de acțiune. Trebuie să elimin discrepanța dintre modul în care îmi petreceam timpul și ceea ce este cu adevărat important pentru mine.

5.  **Trebuie să îi ajut pe ceilalți să își atingă potențialul**

    Pentru că reușita nu este nici șansă nici întâmplare, ea stă ascunsă în sufletul fiecăruia. Trebuie să le arăt celorlalți care sunt secretele și să le descătușez energia internă pentru a-și aduce la suprafață adevărata putere proprie.

Acestea sunt de altfel și cele cinci principii pe baza cărora am scris prima mea carte, *"De-Limitează-te"*.

Nu aș fi supraviețuit fără o schimbare completă de paradigmă. Mi-am dat seama că mă plafonasem mental și că forța gândului este cea mai mare putere cu care am fost înzestrat. Am descătușat-o și m-am ridicat demn din noroi, am ales o direcție și am urmat-o cu determinare.

După trei zile de mers cu pași mici am găsit o gospodărie cu un fânar în care m-am adăpostit peste iarnă. Lângă coșul de la sobă era cald și de mâncare găseam printre semințele rămase între paie. Acolo am întâlnit și câteva vrăbii și niște șobolani cu care am rămas prieten până azi. De la ei am învățat cum să te ferești de pericole atunci când sunt prea mari ca să le înfrunți direct și care este lumea de dincolo de câmp. I-am motivat și pe ei să schimbe lucruri în viața lor: acum una dintre vrăbii conduce o organizație numită "Canari gri", prin care încearcă să convingă oamenii că vrăbiile pot fi animale de companie și unul dintre șoareci a pornit o inițiativă numită "Și noi suntem hamsteri", folosindu de brand-ul pe care hamsterii au reușit să-l dobândească pentru a reduce ura umană față de șoareci și șobolani.

Cum s-a făcut primăvară am plecat din gospodăria binefăcătorilor mei spre oraș, unde am fost primit cu surprindere de către autorități, filmat de televiziunile care nu aveau subiecte de *breaking news* și dus apoi cu onoruri la un spital veterinar, unde am fost eroul unui documentar.

După multe operații și câteva implanturi osul meu e la fel de bun ca înainte de incidentul cu vânătorul. Numai că nu mai vreau să zbor; nu aceasta este menirea și nici misiunea mea.

Acum țin conferințe pe tot mapamondul și zbor, dar la business class. În fond o prepeliță care vorbește este o atracție la orice eveniment. Fac o diferență în viețile altora și acest lucru este cel mai important.

Cu ai mei n-am mai ținut legătura. Am înțeles că își continuă rutina de prepelițe middle-class: rouă, odihnă, boabe, Africa...

Sper că la unul dintre seminariile pe care le voi avea în Bărăgan să vină și Sandi. Să îi spun, cât de important e să o asculte pe mămica, dar în contextul propriului sistem de valori și principii.