---
title: "re-covers: Greierele și Furnica. Jurnalul unei furnici imposibil de mulțumit"
date: "2011-11-03"
time: "18:51"
tags:
  - "ce am mai scris"
  - "fictiune"
  - "recovers"
---
**28 noiembrie**

Am făcut bine că l-am lăsat în frig fără mâncare. E clar că trebuia să învețe ce înseamnă să-ți bați joc de muncă și să fii misogin. Dacă făceam amândoi ce zicea el, muream de foame într-un mare stil. Să ne cheltuim toate bobițele pe nectar și polen în loc să le strângem ar fi fost o nebunie. Acum că a venit frigul, îmi este cu atât mai clar. Am fost o furnică perseverentă și asta cel puțin pe mine m-a salvat.

Nu știm nici unul cum se va descurca mai departe, însă este capabil să-și poarte singur de grijă; doar a mai făcut-o și în alte ierni. Nici nu mă interesează de fapt. Mie îmi va fi bine. Am fost și voi rămâne puternică.

**30 noiembrie**

Totul aici în mușuroi este un dezastru. Eram dezordontă și înainte, dar parcă nu așa. Îmi voi reveni. Viața se va așeza în albia ei, ca Siretul după o viitură. Îmi voi reconstrui podurile și îmi voi reface sufletul după inundațiile de anxietate care mi l-au umplut de neliniște. E ciudat ca un bărbat să îmi facă asta. La naiba!

**2 decembrie**

Mi-am amintit de momentul când l-am cunoscut, întorcându-ne amândoi de la un eveniment despre rolul hexapodelor în ecosistem. Pasiunea intensă pentru artropodologie nu avea cum să ne lase departe unul de celălalt, chit că de la început știam că aparținem la propriu unor specii diferite.

Am tot povestit tot drumul despre cum trebuie să folosim diversitatea noastră pentru a progresa, despre cum că este clar că cel puțin numeric stăpânim lumea, că ar trebui să o facem mai prietenoasă pentru noi, despre cum ar trebui să conviețuim cu unele mamifere și să sârpim păsările care ne decimează atât de mulți semeni.

În toiul discuției antenele ni s-au atins întâmplător și mi-am dat seama pe loc: deși el este orthopteră și eu vespoidea, suntem făcuți unul pentru altul.

**7 decembrie**

Azi s-a împlinit un an de când am părăsit mușuroiul cu o sută de mii de furnici pentru a trăi singură. Este foarte rar pentru o furnică să aibă un astfel de curaj. Dar nu suportam să trebuiască să fac în fiecare zi același lucru, mai ales trebuind să fiu mereu supusă și să accept ordinele tuturor masculilor. Or să îi văd cum își asumă numai ei rolul de apărători ai coloniei. Am și eu drepturi ca oricare insectă.

Acum sunt independentă și aceasta este starea mea firească. Prefer libertatea în detrimentul falsei siguranțe.

**11 decembrie**

Mi-am amintit de cum ne scriam la început folosind poșta olfactivă pneumatică. Comunicăm mai bine prin miros. Așa că preferam să ne trimitem odoare și să scriem ceva pe lângă. Scrisorii îi ia câteva minute să ajungă la destinatar prin labirintul de tuburi, deci poți să schimbi câteva zeci de mesaje pe zi. Ce emanații plăcute, ce mireasme exotice, ce parfum aveau mesajele lui...

Îmi plăcea că îi venea natural să vorbească *gender-neutral* sau că îmi încuraja ideile și mă ajuta atunci când îmi pregăteam un speech despre egalitatea în drepturi. Mă făcea să mă simt o autentică Fourmi de Beauvoir.

**17 decembrie**

Grrr... sper să scap de mahmureala asta nenorocită cât mai repede. Ce noroc că nu are cine să mă ia la rost. Îmi amintesc ce scandal mi-a făcut când m-am împiedicat într-o seară în cele șase picioare, după ce exagerasem cu mâncatul unor semințe fermentate. Mi-a sugerat că beția e o chestie pur masculină și asta a umplut paharul, ca să zic așa. Că el îmi va intezice să îmi bat joc de mine de aici înainte. Toate astea după ce că am muncit ca o sclavă toată vara, în timp ce el încerca fără succes să își construiască o "carieră muzicală" cu *Les Cigales*. În acest context să mai aibă și apucături de șef este revoltător.

În secunda doi l-am părăsit, *of course*. Să-și găsească vreo libelulă supusă dacă are chef să își exercite autoritatea pe cineva. M-a rugat să-i împrumut niște boabe și ceva provizii; să treacă și el iarna cumva. L-am flit-uit instant, la figurat, evident, nu sunt o ucigașă. Nu merita nimic și a înțeles prea târziu că eu sunt o viespe într-un corp de furnică.

**7 ianuarie**

Încălzire globală my-ass. E un frig că nu mai pornesc nici Volgile. Îmi tremură toracele de zici că sunt șarpe cu clopoței, deși abia am ieșit să fac o gaură în zăpadă să mai intre niște aer aici jos.

Cică Greiele ar fi bine, ghici cum, cu o libelulă! I-a săpat ea o gaură în pământ pe lângă o conductă de căldură și hibernează amândoi, liniștit și ignorant, așteptând primăvara.

Retro-sexual nenorocit ce e!

--

București, 3 noiembrie 2011