---
title: "O ficțiune mai veche"
date: "2011-07-19"
time: "07:00"
tags:
  - "ce am mai scris"
  - "fictiune"
---
Am privit-o deja de atâtea ori trecând spre casă încât îi cunosc mersul, gesturile, prietenii, îmbrăcămintea şi aproape tot ce se poate ști despre o femeie pe care ai vazut-o aproape mereu din spatele unui geam. A trecut cred ca aproape un an de cand am zărit-o prima oara. Era o zi destul de mohorâtă, spre sfârsitul primăverii, iar eu eram extraordinar de frustrat că primisem ordin să-mi mut biroul lângă fereastra de la etajul doi al cladirii business in care lucram. Nu îmi place lumina, iar vestea că voi fi așezat chiar lângă geamul ce se pornește de la podea și se oprește fix în tavan mă scotea din minți.\
\
Nu mă uit niciodată la oameni pe stradă, dar atunci nu puteam deloc să mă concentrez. Așa că priveam indiferent trecatorii ce mi se desfăşurau grăbiţi prin fața ochillor. Chipurile lor nu făceau decât să-mi confirme că lumea este la fel de nefericita ca și mine.\
\
Sute și sute de fețe triste. Nu știu de ce am remarcat-o atunci. Era frumoasă, dar nu o puteam vedea prea bine de la distanţă, hainele îi erau de bun gust, dar nu extraordinare, în schimb avea ceva aparte care ma facea să vreau să îi provoc timpului o pauză pentru a mă lasa să o privesc pe îndelete. Era ca un trandafir pe cale să înflorească, un copil pe cale să devină femeie. Am avut sentimentul că acel trandafir trebuie să devină al meu. Sentimentul îmi era cunoscut, pentru că era a multa oară cănd mi-am dorit un trandafir în zadar. M-am învăţat cu neputinţa. Relatiile mele au fost puține și niciodată pornite de mine, toate au începute şi terminate la fel de anost.\
\
Aş fi vrut sa alerg după ea, dar nu ştiam ce să-i spun. Spontaneitatea mă deranjează. Plus că nu aveam cum să o prind din urmă... Unii ar spune ca este dragoste la prima vedere, însă nu este nici pe departe vorba de aşa ceva. Vroiam pur şi simplu un trofeu... şi în câteva secunde a dispărut după colţul străzii, iar eu am continuat resemnat să privesc pe geam.... Sute şi sute de feţe triste.\
\
M-am adaptat până la urmă cu ideea că sunt condamnat la soare şi la a-i observa pe trecători zi de zi prin geam, ca un demiurg plictisit de creaţia sa. Învăţasem să-mi văd de treabă, însă un colţ al privirii era mereu spre stradă. Mă alimentam cu tristeţea oamenilor care mă făcea să mă simt bine ştiind că nu sunt singurul nefericit. Nu îmi place acasă, nu îmi place la serviciu, nu vreau să stau şi nu vreau să plec. Nu iubesc pe nimeni şi în afară de mama acum nu mă mai iubeşte nimeni.\
\
Nu sunt capabil de sentimente atât de adânci. Sau cel puţin nu îmi dau seama de ele. Iubirea poeţilor este o născocire. Sau poate am să o descopăr alături de Clara, pentru că aşa o cheamă pe ea. Pe fata de după geam. Azi am să o văd şi am să-i vorbesc...\
\
A apărut şi a doua zi, a trecut la fel de repede prin faţa privirii mele, înainte să dispară după acelaşi colţ de stradă. Apoi şi a treia zi şi a patra zi la fel. A cincea nu a mai venit, dar apoi a reapărut. Era o certitudine la fel de plăcută precum biscuitele de care mă bucur alături de machiatto-ul de la ora 8 jumătate. Când trecea ea forfota din birou se topea în depărtare, şi parcă şi maşinile mergeau mai încet pe stradă, ca să o admire...\
\
A doua săptămână a lipsit vreo trei zile şi chestia asta m-a făcut să fiu nervos toate după-amiezile. Era mijlocul lui mai; chiar şi mama mă întreba seara la ceai ce este cu mine. Doar nu era să-i zic. Inventam ceva că rapoartele financiare nu au ieşit bine şi că suntem expuşi pe nu ştiu ce pieţe externe. Şi mă lăsa în pace, pentru că nu înţelegea despre ce vorbesc, dar mă credea.\
\
Cel mai supărat am fost în săptămâna în care am văzut-o de mână cu un băiat. Simţeam dureri în piept şi în stomac iar o senzaţie de frig mă cuprindea în tot corpul, deşi era august. Nu puteam să accept că ea mă trădează, chit că nu mă cunoştea, iar că el îmi fura acest premiu pe care mi-l doream, fără să fi făcut însă nimic să îl am. Simţeam că această madonă îmi este murdărită de mâini străine. Puneam la cale fel şi fel de planuri diabolice, îmi doream când să fiu un lunetist, când să pot să plătesc pe cineva să-l aranjeze pe nenorocit. Relaţia lor nu părea însă să meargă bine, după ce feţe aveau mergând unul lângă altul. Iar într-o zi când veneau din nou împreună, el s-a oprit, s-a uitat agresiv la ea, i-a arătat cu degetul spre încheietura mâinii, ea a dat din cap că da. Apoi a părut că îi pune o întrebare la care ea a gesticulat un nu categoric şi sfidător. De la treizeci de metri nu auzeam ce vorbeau; el s-a supărat atât de tare că i-a mai zis vreo două şi a plecat în direcţia opusă... Şi frigul a dispărut. De atunci nu l-am mai văzut cu ea. Şi tot de atunci am început să nu mai las lucrurile la voia întâmplării.\
\
După vreo două minute de confuzie în care nu ştia ce să facă, şi-a continuat mândră drumul obişnuit. Iar eu m-am ridicat de pe scaun şi mi-am cerut primul concediu după 5 ani. Au fost miraţi de cererea mea de a lipsi o săptămână chiar de a doua zi, însă nu au avut ce face, chiar dacă în noiembrie e mult de muncă. Nu mă agrea nici unul prea mult, însă aveau nevoie de mine. Dar ce-mi pasă? Eu sunt la serviciu ca să muncesc nu să-mi fac prieteni.\
\
A doua zi am urmărit-o. Pentru prima oară am trecut de colţul străzii împreună. De aproape şi fără geam era mai frumoasă decât mi-o putusem imagina. Nu mă jucasem niciodată de-a detectivul nici nu îmi făcea plăcere . Eram departe în afara zonei de confort, dar trebuia să știu cu orice preţ lucruri despre ea. Am reuşit să aflu destul de multe în mai puţin de două săptămâni, vorbind cu vecini, cu colegi şi chiar cu rude. O chema Clara, avea un frate Relu şi doi părinţi oameni simpli. Crescuse în cartier, era deosebit de inteligentă, dar mai mult decât şcoala îi plăcea să citească sute de cărţi de la anticariat şi să asculte muzică stranie. Mai avea puţin şi termina facultatea de istorie, ceea ce înseamnă că şi ea poate ştia câte ceva despre străbunicii mei. Nu-i voi spune însă nimic azi când ne vom vedea...\
\
Ştiam aproape totul despre prezentul ei, pentru că trecutul, deşi mă rodea, preferam să nu i-l ştiu încă. Privirile pline de subînţeles ale foştilor ei colegilor de şcoală mi-au făcut să îmi doresc să nu aflu mai multe. Important pentru mine era nu ce a fost sau ce este, ci doar putea să devină Clara alături de mine.\
Am făcut tot ce mi-a stat în putinţă să găsesc legături cu familia ei, pe care să o conving ca eu sunt o cunoştinţă bună pentru fata lor. Aş fi putut să merg la ea direct, dar mi-a fost mereu frică. Frustrarea că nu găseam cum să îi vorbesc era consolată de minutul în care puteam să o privesc pe Clara din spatele geamului în fiecare zi. Ce decizie inspirată să fiu mutat la geam, şi ce întâmplare fericită că lucrez atât de aproape de Facultatea de Istorie...\
\
Am emoţii şi nu mă înţeleg. Totul a fost pregătit cu grijă. Tatăl ei a convins-o să mă vadă azi, povestindu-i Clarei atât de multe lucruri despre mine câte am rugat-o eu pe mătușă-mea să-i spună... şi nu sunt puţine.\
În cinci minute mă va cunoaşte în sfârşit. De fapt poate chiar mai repede, dacă nu va întârzia. Locul pe care l-am ales este perfect, trotuarul pe care am văzut-o prima oară, trotuarul pe care s-a despărţit de acela. Este locul în care eu o voi re-găsi ca persoană şi ea mă va primi în viaţa ei aşa cum merit. Sunt curios ce va purta azi pentru mine. Sper să fie acea rochie de vară pe care o poartă când e soare. Azi e soare şi aşa va fi mereu.\
\
M-am aşezat vis-a-vis, în spatele unei vitrine, pentru că vreau să o văd din spatele geamului o ultimă dată, înainte ca universul nostru să se schimbe ireversibil în bine. Sunt curios ce i-o fi spus băiatul acela atunci. Ce însemna acel gest ca o seringă în braţ. Ceva totuşi nu se potriveşte; Clara este o fiinţă perfectă, şi ceilalţi o pot supara pe ea, nu si invers...\
\
Când ridic privirea şi o văd sosită mă cuprinde o stare de linişte. A venit... Este aici pentru mine, am învins! M-aş repezi chiar acum prin vitrină, peste stradă, peste mașini și peste oameni și aș strânge-o în brațe punându-i capul pe pieptul meu, mângâindu-i părul cu toate degetele, sărutându-i creștetul. Și nu i-aș da drumul niciodată. Niciodată! Dar... dar de ce e îmbrăcată în fusta asta de blugi? ...De ce are tricoul ăsta roz? Cu cine crede că se întâlnește, cu vreo colegă ratată din școala aia de cartier a ei? Eu sunt altfel, eu o vreau proaspătă și pură, nu așa ca o vânzătoare în Obor. E clar că nu-i pasă de mine. Că nu dă doi bani pe persoana mea. De ce? Eu nu merit așa ceva. Sunt un băiat bine crescut și ar trebui să știe asta de la mătuşă-mea. Dar lasă că o schimb eu, și va ști cum să se îmbrace. Important e mai întâi să mă asigur că este a mea. Așa că am să o iert pentru cum s-a comportat cu mine azi.\
\
Ies pe ușa magazinului uitându-mă o ultimă dată la ea de departe. De acum va fi altfel. Am să o cuceresc și am să o fac să mă iubească, să mă adore. Îi voi fi și un fel de iubit și un fel de tată în același timp. Iar peste un an vom fi tot aici, aparent la fel, dar în realitate atât de schimbați. Vom fi împreună ca doi eroi din romanele bune: vom fi încheiat un an, o iterație a vieții noastre arătând la fel, vorbind la fel. O poveste care începe și se termină în același loc. Se termină ? Se termină ?!?...\
\
Nu vreau să se termine. Pentru că ea trebuie să mă iubească mereu, iar eu să am grijă de ea în continuare. Nu vreau să o pierd și mai ales nu atât de repede. Un an e prea puțin față de eternitatea pe care ar trebui să o petrecem împreună. Dar peste un an am putea fi tot aici, iar eu să fiu acel băiat cu care se ceartă și pe care îl părăsește. Oare aș putea să am curaj să-i zic vreodată ceva rău ei? Poate că da. Cred că nu. Relația noastră va fi fost una frumoasă. Pentru că întânirea de azi a mers bine. Și pentru că ea este impresionată că eu o înțeleg mai bine decât toți copii cu care s-a văzut până acum. Mă va accepta și mă va admira. O voi învăța istorie, pentru că știu, o voi învăța cum să se îmbrace, cum să se comporte, va fi o variantă îmbunătățită a mea. Voi fi mai dur cu ea decât sunt cu mine, pentru că doar așa poate să se transforme. Dar dacă în loc să o transform eu pe ea mă va tranforma ea pe mine? Dacă eu voi deveni ceea ce este ea acum?\
\
Și apoi după un an mă va părăsi pentru vreun copil de-o seamă cu ea care are motocicletă și merge cu ea în cluburi în loc să o îndemne să meargă la concerte de Bach? Probabil îmi voi da seama de ce vrea să facă cu mult timp înainte, dar nu o voi opri, pentru că în sinea mea știu deja că este mai bine pentru ea să nu se încurce cu un bătrân ca mine. Și pentru că eu o vreau ca pe o jucărie, în timp ce ea mă vrea ca pe cineva care o iubește adevărat, ca într-un roman de Jane Austen pe care îl savurează noaptea înainte să se culce. Îmi va spune că trebuie să o iubesc cum mă iubește ea pe mine. Dar nu se poate, pentru că eu nu pot să iubesc. Pot să admir și să îngrijesc. Apoi va pleca așa, pur și simplu, de lângă mine, viața ei urmându-și un cursul fad pe care l-a avut fără mine, iar viaţa mea fiind lipsită de sensul pe care mi l-a creat cunoscând-o pe ea. Va trebui să sufere, pentru că m-a făcut să sufăr. Trebuie să plătească pentru ce mi-a făcut.\
\
Mașinile pe stradă și lumea din jur parcă nu mai există. Strada s-a liniștit dintr-o dată. Mă apropii de ea. Îi simt deja mirosul care va rămâne pe pernă ani buni după ce ea nu va mai fi cu mine. Nu pare că mă recunoaște; mă privește curios, arogant și sfidător. Asta este chiar culmea!\
\
Sunt furios. Nu pot să mă abţin şi o lovesc. Se uită la mine uluită, probabil mai mult de șoc decât de durere. Ochii ei sunt acum un amestec de ură, dârzenie și spaimă. Ce... am... făcut...??? Trebuia să îi țin capul pe piept și să îi sărut creștetul, iar eu am lovit-o? Da! Pentu că merită. M-a rănit. Nu pentru că m-a lăsat atunci când o iubeam, ci pentru că mi-a dovedit că nu sunt suficient de bun să o pot face cu adevărat a mea. Mi-a desființat ceea ce aveam cel mai de preț. Respectul meu pentru mine. O las și plec.\
\
După vreo două minute de confuzie în care nu ştia ce să facă, şi-a continuat probabil mândră drumul obişnuit. Eu mă întorc spre casă. Sute şi sute de feţe triste îmi taie calea. Dar azi nu mă ajută. Pentru că nici una nu simte ceea ce simt eu.