---
title: "De la fiecare după posibilități, fiecăruia după nevoi"
date: "2013-03-19"
time: "14:37"
tags:
  - "ce am mai scris"
  - "opinie"
  - "cipru"
  - "ue"
  - "xx"
---
Dacă un vecin îți bagă mâna în portofel și ia o parte din bani sub privirile încurajatoare ale celorlalți vecini și ale polițistului, spunând că banii i se cuvin, fiindcă tu îi ai și el are nevoie de ei, atunci comunitatea în care trăiești are o mare problemă. Ce faci însă atunci când această comunitate este chiar lumea în care trăiești?

În 16 martie 2013, într-o sâmbătă dimineață, statul cipriot anunța intenția sa oficială de "reține un comision" de 6,75% pentru depozitele sub o sută de mii de euro și 9,9% pentru depozitele de peste o sută de mii de euro din băncile sale.

Vestea că un stat al Uniunii Europene își jefuiește cetățenii, nu din proprie inițiativă, ci presat de aceeași Uniune, este mai gravă decât cele mai grave dintre știrile pe care le-am auzit vreodată.

Mai gravă decât cutremurul din Japonia de acum doi ani, pentru că acela nu putea fi evitat, mai gravă decât atentatele de la 11 septembrie 2001, pentru că acolo adversarii erau cunoscuți, războiul lor era declarat de dinainte, iar răul a venit de la cei răi și binele de la cei buni.

Acum cel bun este agresor și de aici grozăvia situației. Cel ce produce această ticăloșie este cel care trebuie să mă apare atunci când guvernul meu ar fi încerca să facă vreo bubă în drepturile mele. Este cel care îmi controlează sistematic același Guvern și îl sfătuiește cu morcovul într-o mână și cu biciul în cealaltă.

Cum să reacționezi deci atunci când îngerul tău păzitor se dovedește a fi de fapt un tâlhar?

Am purces pe site-ul Uniunii cu scopul de a găsi fundamentul moral și legal al acestei decizii euro-cipriote. Intru și găsesc pe europa.eu:

*"Drepturile omului, democraţia şi statul de drept sunt valori fundamentale ale Uniunii Europene. Înscrise în tratatul fondator, acestea au fost consolidate odată cu adoptarea de către UE a Cartei drepturilor fundamentale."*

Continuă:

*"Uniunea Europeană consideră că drepturile omului sunt universale şi indivizibile. UE le promovează şi le apără atât pe plan intern, cât şi în cadrul relaţiilor cu ţările din afara ei."*

Caut apoi și găsesc, în engleză, *Carta drepturilor fundamentale*. Merg la articolul 17 (traducere proprie):

*"Orice persoană are dreptul de a deține în proprietate, de a utiliza, de a dispune și de a lăsa moștenire bunurile sale legal dobândite. Nimeni nu poate fi lipsit de bunurile sale, cu excepția cazurilor de interes public și în condițiile prevăzute de lege, în schimbul unei despăgubiri juste acordate în timp util pentru pierderea lor. Folosința bunurilor poate fi reglementată prin lege, în măsura în care este necesar, pentru interesul general."*

Merg apoi și la *Carta drepturilor omului*, în fond suntem pe lângă eurpeni și oameni la bază:

*"1. Orice persoană are dreptul la proprietate, atât singură, cât și în asociație cu alții. 2. Nimeni nu poate fi lipsit în mod arbitrar de proprietatea sa."*

Se pare că aceste drepturi fundamentale au devenit recent opționale. Am din păcate un deja-vu. În 1947, pe 16 august, tot într-o sâmbătă, a fost promulgată legea 287, reforma monetară. Douăzeci de mii de lei vechi deveneau un leu nou, iar prețul unui kilogram de aur era în atunci 168 de mii de lei noi, adică aproximativ cât acum. Dacă erai norocos puteai să schimbi maxim 150 de lei, dacă nu, 75 de lei. Restul banilor puteai să-i arzi, nu mai foloseau la altceva.

Or, diferența între ce s-a întâmplat atunci, într-un regim bolșevic totalitar și ce se întâmplă acum în Cipru este doar una de procent, nu de principiu, ceea ce este revoltător.

Comuniștii au avut pretenția că așa îi lovesc pe chiaburii care s-au îmbogățit pe spinarea muncitorimii și salvează țara. Acum pretextul este că salvezi țara lovind în mafia rusă și în euro-spălătorii de bani. Un argument solid, dealtfel, în fond l-a folosit și Irod acum destui ani. Dacă-i ucizi pe toți, sigur printre ei sunt și cei care trebuie.

Așa că ciuda dezgustului pe care mi-l produce circul politic intern, mă bucură că zgomotul său acoperă aceste evenimente. E mai bine poate ca lumea să nu știe ce se întâmplă, pentru că în ignoranță să poată să își păstreze încrederea.

Iar încrederea este ceva care se construiește greu și se pierde într-o clipită. Și modul de viață pe care îl avem, și el construit tot greu se bazează aproape exclusiv pe încredere. E păcat că îl distrug pentru așa puțini arginți.