---
title: "\"Simboluri ale democrației\""
date: "2014-05-11"
time: "12:03"
tags:
  - "opinie"
  - "Romania"
---
Ridicam degetul acum câteva săptămâni spre Ministerul Educației și Centrul Naţional de Evaluare şi Examinare (C.N.E.E.), aflat în subordinea sa. Acuzam CNEE că a organizat o licitație proastă, nedreaptă, întârziată.

Iată însă că această licitație nu numai că are atributele de mai sus, ci se pare că este și ilegală. Federația Editorilor din România, respectiv două companii private au contestat licitația, iar Consiliul National de Solutionare a Contestatiilor a decis suspendarea acesteia ([detalii](http://www.hotnews.ro/stiri-esential-17189308-licitatia-pentru-manuale-digitale-fost-suspendata-consiliul-national-solutionare-contestatiilor.htm){target="_blank"}).

Ca de obicei. Ministerul Educației nu a reacționat în vreun fel. Pe site-ul edu.ro, azi, la patru zile după suspendare, singurul comunicat de presă nou este că domnul Pricopie confirmă Biblioteca Centrală Universitară ca fiind un simbol al democrației românești. Atât.

Mă aștept însă să reacționeze și cred că modul în care o vor face va fi previzibil și caragialesc, în modul cel mai îngrozitor al acestuia. Ministrul sau directorul CNEE vor ieși public declarând, cu lacrimi în ochi, că *Baronii manualelor ne-au învins... Am încercat să facem totul pentru propășirea educațională a aceste națiuni, pentru acest popor unic, pentru acești copii minunați \[suspin\], dar ei iată că ei au reușit să ne blocheze inițiativa în ciuda eforturilor noastre supraomenești de reformare.*

Vor continua: *interesele lor sunt comerciale, ei vor bani, nu să fie bine pentru copii. Am încercat să facem totul așa cum trebuie, dar ei nu ne lasă.*. Desigur. Doar nu ne așteptăm la *Este vina noastră ca Minister și ca CNEE pentru că n-am pus pe cine trebuie să organizeze treaba, pentru că nu ne-am consultat în fapt cu nimeni, pentru că am încercat să ne păstrăm relațiile cu cine știe cine. Ne este rușine, avem un plan și încercăm sincer să facem lucrurile mai bine de aici înainte*. Dar nu.

Dacă și CNEE sau Ministerul Educației ar fi simboluri ale democrației, ar trebui să explice ce se întâmplă, nu să tacă în sfidare, făcându-se că nu s-a întâmplat nimic.

Dacă ar fi simboluri ale democrației, ar trebui să ne anunțe cine este responsabil pentru această grozăvie și respectiv cum procedează cu el, respectiv cum fac să rezolve problema acum astfel încât așa ceva să nu se mai întâmple vreodată.

Cine sunt în fapt cei care gestionează introducerea acestor tehnologii noi în școală? E simplu de aflat: uitați-vă la site-ul lor, [http://www.rocnee.eu/,](http://www.rocnee.eu/,){target="_blank"} și vedeți cum arată, cum se navighează, ori cum sunt puse imaginile în acest site. Ei, cei care nu sunt în stare să aibă un site mai bun decât al băcăniei din colț, decid soarta manualelor digitale (care au majoritatea ADN-ului lor comun cu un site), manuale digitale care vor fi folosite de milioane de elevi, mulți ani de aici înainte.

Sunt incompetenți, ne consumă banii din taxe degeaba și, cu toate acestea, rămân acolo primindu-și lefurile. N-a fost nimeni dat afară, n-a fost nimeni avertizat. Nimeni nu este responsabil pentru acest fiasco.

E genul de nedreptate la care ți se face rău fizic dacă te gândești la ea. Într-o companie privată, pentru a zecea parte din ce au făcut ei cu această inițiativă, ești concediat instantaneu și deseori urmărit penal pentru pagubele produse. La MEN ori CNEE, însă nu. Acolo e bine. Vivat democrația și beneficiarii dânsei. Deloc simbolici.