---
title: "Maleficent"
date: "2014-06-08"
time: "00:04"
tags:
  - "recenzii"
  - "film"
---
Pentru că nu am putut suporta presiunea de a mă plictisi la o finală de Roland Garros cu o miză atât de mare, am ocupat unul dintre de locurile lăsate libere de eurosportivi în fața celui mai mare ecran de cinema din București.

[]{#start}

Am văzut Maleficent, pe care îl așteptam încă de dinainte ca Lana del Rey să-mi zică *I know you* în [Once Upon a Dream](http://www.youtube.com/watch?v=8waJ7W3QcJc){target="_blank"} (pe melodia lui [Ceaikovski](http://www.youtube.com/watch?v=2Sb8WCPjPDs){target="_blank"} aleasă deloc întâmplător).

Deși este făcut de Disney, duceți-vă cu copiii doar dacă știu că nu i-a adus barza. Filmul nu are nimic deocheat, doar că nivelul de violență și complexitatea decorurilor va face ca unii din cei mici să exclame *Îmi este frică de toți, mai bine rămâneam acasă...*.

Nu vă așteptați însă ca povestea să fie mai complexă decât un Grimm adaptat la retorica de secol curent. Pentru vibrații emoționale ai carțile, teatrul sau cinemateca. Te duci la mall la 3D pentru spectacol, pac-pac și vertijul zborului cu fundul pe scaun. Toate, lucruri la care Maleficent excelează și probabil crează noi standarde.

De fapt majoritatea trăirii mi-a fost creată nu de la evoluția previzibilă a poveștii, ci de la admirația fără rezerve pentru scenografii, pentru cei care au făcut storyboarding-ul și cei au realizat randările lumilor din film. N-am putut să mă gândesc la saltul uriaș de la Mikey Mouse fluierând la timonă în [Steamboat Willie](http://www.youtube.com/watch?v=BBgghnQF6E4){target="_blank"} acum 85 de ani la perfecțiunea punerii pe ecran a unui basm în 2014. Purpuriul ființelor luminescente se reflectă perfect pe fețele celor din jur, la fel metamorfozele personajelor este peste imaginația din timpul lecturii. Mă întreb optimist unde vom fi ca specie peste încă 85 de ani.

Pe scurt, mi s-a părut un film de top la efecte vizuale și coloană sonoră, care stă excelent la capitolul divertisment, fără mari răscoliri emoționale, potrivit pentru 12+ ani. Mă bucur că l-am văzut, dar de revăzut l-aș revedea doar într-un loc în care să pot pune pauză și să derulez pentru a admira perfecțiunea micilor detalii.

\[\[MORE\]\]